#!/usr/bin/env bash

#THe script affiche des informations sur les sous-domaines d'un domaine donné.

# Fonction pour afficher les informations sur un sous-domaine spécifique
print_subdomain_info() {
    local subdomain="$1"
    local domain="$2"
    dig_output=$(dig "$subdomain.$domain" | awk '/^;; ANSWER SECTION:$/,/^$/ {if ($1 == subdomain "." domain ".") print "The subdomain", subdomain, "is a", $4, "record and points to", $5}')
    echo "$dig_output"
}

# Fonction pour afficher les informations sur les sous-domaines par défaut
print_default_subdomains_info() {
    local domain="$1"
    print_subdomain_info "www" "$domain"
    print_subdomain_info "lb-01" "$domain"
    print_subdomain_info "web-01" "$domain"
    print_subdomain_info "web-02" "$domain"
}

# Vérification des arguments
if [ $# -eq 0 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain="$1"
subdomain="$2"

# Affichage des informations sur les sous-domaines
if [ -z "$subdomain" ]; then
    print_default_subdomains_info "$domain"
else
    print_subdomain_info "$subdomain" "$domain"
fi
