#!/bin/bash
# Ce script transfère un fichier d'un client à un serveur via SCP

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

scp -i "${PATH_TO_SSH_KEY}" -o StrictHostKeyChecking=no "${PATH_TO_FILE}" "${USERNAME}@${IP}:~/"
