#!/bin/bash
# Configuration de nginx pour rediriger /redirect_me vers une autre page

# Assurez-vous que nginx est installé
apt-get install nginx -y

# Configurer la redirection
echo 'server {
    listen 80;
    server_name localhost;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}' > /etc/nginx/sites-available/default

# Recharger nginx pour appliquer la configuration
nginx -s reload
