#!/usr/bin/env bash
# Script that installs and configures HAProxy as a load balancer

# Install HAProxy
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

# Configure HAProxy
server_config=\
"
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
    ssl-default-bind-options no-sslv3

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend load_balancer
        bind *:80
        mode http
        default_backend webservers

backend webservers
        balance roundrobin
        server 520532-web-01 52.23.177.252:80 check
        server 520532-web-02 18.204.7.7:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Activation de HAproxy pour le démarrage par le script init.
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Configuration pour que HAproxy soit gérable via un script init.
sudo systemctl enable haproxy
sudo service haproxy restart
